"""Generate a small synthetic ICSR workbook for local runs and CI."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

COLUMNS = [
    "safetyreportid",
    "safetyreportversion",
    "serious",
    "seriousnessdeath",
    "seriousnesslifethreatening",
    "seriousnesshospitalization",
    "seriousnessdisabling",
    "seriousnesscongenitalanomali",
    "seriousnessother",
    "fulfillexpeditecriteria",
    "primarysourcecountry",
    "occurcountry",
    "reporttype",
    "report_date",
    "patient_patientonsetage",
    "patient_patientonsetageunit",
    "patient_patientsex",
    "patient_patientweight",
    "primarysource_qualification",
    "patient_summary_narrativeincludeclinical",
    "patient_reaction_reactionmeddrapt",
    "patient_reaction_reactionoutcome",
    "patient_reaction_reactionmeddraversionpt",
    "patient_drug_drugcharacterization",
    "patient_drug_medicinalproduct",
    "patient_drug_activesubstance_activesubstancename",
    "patient_drug_drugdosagetext",
    "patient_drug_drugstructuredosagenumb",
    "patient_drug_drugstructuredosageunit",
    "patient_drug_drugadministrationroute",
    "patient_drug_drugindication",
    "patient_drug_actiondrug",
    "patient_drug_drugstartdate",
    "patient_drug_drugenddate",
]


def build_sample_rows() -> list[dict]:
    return [
        {
            "safetyreportid": 1001,
            "safetyreportversion": 1,
            "serious": "1",
            "seriousnessdeath": "0",
            "seriousnesslifethreatening": "1",
            "seriousnesshospitalization": "1",
            "seriousnessdisabling": "0",
            "seriousnesscongenitalanomali": "0",
            "seriousnessother": "0",
            "fulfillexpeditecriteria": "1",
            "primarysourcecountry": "US",
            "occurcountry": "US",
            "reporttype": "1",
            "report_date": "2025-01-15",
            "patient_patientonsetage": 72,
            "patient_patientonsetageunit": "year",
            "patient_patientsex": "2",
            "patient_patientweight": 68,
            "primarysource_qualification": "1",
            "patient_summary_narrativeincludeclinical": "Elderly patient reported hypotension.",
            "patient_reaction_reactionmeddrapt": "Hypotension,Dizziness",
            "patient_reaction_reactionoutcome": "recovering,recovering",
            "patient_reaction_reactionmeddraversionpt": "26.1,26.1",
            "patient_drug_drugcharacterization": "1",
            "patient_drug_medicinalproduct": "Concor",
            "patient_drug_activesubstance_activesubstancename": "BISOPROLOL FUMARATE",
            "patient_drug_drugdosagetext": "5 mg daily",
            "patient_drug_drugstructuredosagenumb": "5",
            "patient_drug_drugstructuredosageunit": "mg",
            "patient_drug_drugadministrationroute": "oral",
            "patient_drug_drugindication": "hypertension",
            "patient_drug_actiondrug": "dose reduced",
            "patient_drug_drugstartdate": "20240101",
            "patient_drug_drugenddate": "",
        },
        {
            "safetyreportid": 1001,
            "safetyreportversion": 2,
            "serious": "1",
            "seriousnessdeath": "0",
            "seriousnesslifethreatening": "1",
            "seriousnesshospitalization": "1",
            "seriousnessdisabling": "0",
            "seriousnesscongenitalanomali": "0",
            "seriousnessother": "0",
            "fulfillexpeditecriteria": "1",
            "primarysourcecountry": "US",
            "occurcountry": "US",
            "reporttype": "1",
            "report_date": "2025-01-20",
            "patient_patientonsetage": 72,
            "patient_patientonsetageunit": "year",
            "patient_patientsex": "2",
            "patient_patientweight": 68,
            "primarysource_qualification": "1",
            "patient_summary_narrativeincludeclinical": "Updated version of the same case.",
            "patient_reaction_reactionmeddrapt": "Hypotension,Dizziness,Bradycardia",
            "patient_reaction_reactionoutcome": "recovering,recovering,unknown",
            "patient_reaction_reactionmeddraversionpt": "26.1,26.1,26.1",
            "patient_drug_drugcharacterization": "1",
            "patient_drug_medicinalproduct": "Concor",
            "patient_drug_activesubstance_activesubstancename": "BISOPROLOL FUMARATE",
            "patient_drug_drugdosagetext": "5 mg daily",
            "patient_drug_drugstructuredosagenumb": "5",
            "patient_drug_drugstructuredosageunit": "mg",
            "patient_drug_drugadministrationroute": "oral",
            "patient_drug_drugindication": "hypertension",
            "patient_drug_actiondrug": "dose reduced",
            "patient_drug_drugstartdate": "20240101",
            "patient_drug_drugenddate": "",
        },
        {
            "safetyreportid": 1002,
            "safetyreportversion": 1,
            "serious": "1",
            "seriousnessdeath": "1",
            "seriousnesslifethreatening": "0",
            "seriousnesshospitalization": "0",
            "seriousnessdisabling": "0",
            "seriousnesscongenitalanomali": "0",
            "seriousnessother": "0",
            "fulfillexpeditecriteria": "1",
            "primarysourcecountry": "DE",
            "occurcountry": "DE",
            "reporttype": "1",
            "report_date": "2025-03-02",
            "patient_patientonsetage": 81,
            "patient_patientonsetageunit": "year",
            "patient_patientsex": "1",
            "patient_patientweight": 74,
            "primarysource_qualification": "1",
            "patient_summary_narrativeincludeclinical": "Fatal case with acute kidney injury.",
            "patient_reaction_reactionmeddrapt": "Acute kidney injury,Death",
            "patient_reaction_reactionoutcome": "fatal,fatal",
            "patient_reaction_reactionmeddraversionpt": "26.1,26.1",
            "patient_drug_drugcharacterization": "1,2",
            "patient_drug_medicinalproduct": "Bisoprolol,Aspirin",
            "patient_drug_activesubstance_activesubstancename": "BISOPROLOL,ACETYLSALICYLIC ACID",
            "patient_drug_drugdosagetext": "2.5 mg daily,100 mg daily",
            "patient_drug_drugstructuredosagenumb": "2.5,100",
            "patient_drug_drugstructuredosageunit": "mg,mg",
            "patient_drug_drugadministrationroute": "oral,oral",
            "patient_drug_drugindication": "heart failure,prophylaxis",
            "patient_drug_actiondrug": "unknown,unknown",
            "patient_drug_drugstartdate": "20231201,20231201",
            "patient_drug_drugenddate": ",",
        },
        {
            "safetyreportid": 1003,
            "safetyreportversion": 1,
            "serious": "0",
            "seriousnessdeath": "0",
            "seriousnesslifethreatening": "0",
            "seriousnesshospitalization": "0",
            "seriousnessdisabling": "0",
            "seriousnesscongenitalanomali": "0",
            "seriousnessother": "0",
            "fulfillexpeditecriteria": "0",
            "primarysourcecountry": "IN",
            "occurcountry": "IN",
            "reporttype": "1",
            "report_date": "2025-06-10",
            "patient_patientonsetage": 45,
            "patient_patientonsetageunit": "year",
            "patient_patientsex": "2",
            "patient_patientweight": 61,
            "primarysource_qualification": "3",
            "patient_summary_narrativeincludeclinical": "Non-serious fatigue report.",
            "patient_reaction_reactionmeddrapt": "Fatigue",
            "patient_reaction_reactionoutcome": "recovered",
            "patient_reaction_reactionmeddraversionpt": "26.1",
            "patient_drug_drugcharacterization": "1",
            "patient_drug_medicinalproduct": "Bisoprolol",
            "patient_drug_activesubstance_activesubstancename": "BISOPROLOL",
            "patient_drug_drugdosagetext": "2.5 mg daily",
            "patient_drug_drugstructuredosagenumb": "2.5",
            "patient_drug_drugstructuredosageunit": "mg",
            "patient_drug_drugadministrationroute": "oral",
            "patient_drug_drugindication": "hypertension",
            "patient_drug_actiondrug": "dose not changed",
            "patient_drug_drugstartdate": "20250201",
            "patient_drug_drugenddate": "",
        },
        {
            "safetyreportid": 2001,
            "safetyreportversion": 1,
            "serious": "1",
            "seriousnessdeath": "0",
            "seriousnesslifethreatening": "0",
            "seriousnesshospitalization": "1",
            "seriousnessdisabling": "0",
            "seriousnesscongenitalanomali": "0",
            "seriousnessother": "0",
            "fulfillexpeditecriteria": "0",
            "primarysourcecountry": "FR",
            "occurcountry": "FR",
            "reporttype": "1",
            "report_date": "2025-02-08",
            "patient_patientonsetage": 30,
            "patient_patientonsetageunit": "year",
            "patient_patientsex": "1",
            "patient_patientweight": 80,
            "primarysource_qualification": "1",
            "patient_summary_narrativeincludeclinical": "Unrelated product case.",
            "patient_reaction_reactionmeddrapt": "Nausea",
            "patient_reaction_reactionoutcome": "recovered",
            "patient_reaction_reactionmeddraversionpt": "26.1",
            "patient_drug_drugcharacterization": "1",
            "patient_drug_medicinalproduct": "Metformin",
            "patient_drug_activesubstance_activesubstancename": "METFORMIN",
            "patient_drug_drugdosagetext": "500 mg",
            "patient_drug_drugstructuredosagenumb": "500",
            "patient_drug_drugstructuredosageunit": "mg",
            "patient_drug_drugadministrationroute": "oral",
            "patient_drug_drugindication": "diabetes",
            "patient_drug_actiondrug": "unknown",
            "patient_drug_drugstartdate": "20250101",
            "patient_drug_drugenddate": "",
        },
    ]


def write_sample(output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    frame = pd.DataFrame(build_sample_rows(), columns=COLUMNS)
    frame.to_excel(output_path, index=False)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a synthetic ICSR Excel sample.")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parents[1] / "data" / "Bisoprolol_icsr_sample.xlsx"),
    )
    args = parser.parse_args()
    path = write_sample(Path(args.output))
    print(f"Wrote sample dataset to {path}")


if __name__ == "__main__":
    main()
