"""
llm_pipeline.py

Controlled language-generation layer for the Bisoprolol ICSR
PADER-style reporting pipeline.

Architecture:

    evidence.json
          |
          v
    Section-specific evidence
          |
          v
    Qwen2.5-0.5B-Instruct
          |
          v
    Generated section
          |
          v
    Grounding / Claim Validation
          |
          +---- VALID ----> Final Report
          |
          +---- INVALID --> FLAG FOR HUMAN REVIEW


IMPORTANT:
    - This module NEVER reads the raw Excel dataset.
    - This module NEVER calculates safety statistics.
    - This module NEVER performs causal inference.
    - The Evidence JSON is the source of truth.
"""


from pathlib import Path
import json
import re
from typing import Dict, List, Any, Tuple
from prompts import get_prompt

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
)


# ============================================================
# CONFIGURATION
# ============================================================

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

MAX_INPUT_TOKENS = 2048
MAX_NEW_TOKENS = 180
NUM_BEAMS = 1

EVIDENCE_FILE = Path(
    "output/evidence.json"
)

REPORT_FILE = Path(
    "output/pader_report.md"
)



# ============================================================
# MODEL LOADING
# ============================================================

def load_model():
    """
    Load Qwen2.5-0.5B-Instruct on CPU.

    No GPU is required.
    """

    print("=" * 60)
    print("Loading Hugging Face model")
    print("=" * 60)

    print(f"Model: {MODEL_NAME}")
    print("Device: CPU")

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME
    )

    model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME
    )

    model.to("cpu")

    model.eval()

    print("Model loaded successfully.")

    return tokenizer, model


# ============================================================
# EVIDENCE LOADING
# ============================================================

def load_evidence() -> Dict[str, Any]:
    """
    Load Evidence JSON generated by analysis.py.
    """

    if not EVIDENCE_FILE.exists():

        raise FileNotFoundError(
            f"Evidence file not found: "
            f"{EVIDENCE_FILE}"
        )

    with open(
        EVIDENCE_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        evidence = json.load(file)

    if not isinstance(evidence, dict):

        raise ValueError(
            "Evidence JSON must contain "
            "a JSON object."
        )

    return evidence


# ============================================================
# JSON SECTION EXTRACTION
# ============================================================

def get_evidence_section(
    evidence: Dict[str, Any],
    section_name: str
) -> Dict[str, Any]:
    """
    Extract only the relevant Evidence JSON
    for a report section.

    The model should receive the smallest possible
    evidence context.
    """

    section_map = {

        "narrative_summary": [
            "reporting_period",
            "case_summary",
            "seriousness",
            "demographics",
            "outcomes",
            "limitations",
        ],

        "summary_analysis": [
            "case_summary",
            "seriousness",
            "demographics",
            "outcomes",
            "limitations",
        ],

        "reaction_analysis": [
            "reactions",
            "seriousness",
            "limitations",
        ],

        "serious_alert_analysis": [
            "case_summary",
            "seriousness",
            "alerts",
            "limitations",
        ],

        "trend_interpretation": [
            "reporting_period",
            "trends",
            "reactions",
            "limitations",
        ],
    }

    keys = section_map.get(
        section_name,
        []
    )

    return {
        key: evidence.get(key)
        for key in keys
    }


# ============================================================
# TEXT GENERATION
# ============================================================

def generate_text(
    prompt: str,
    tokenizer,
    model
) -> str:

    # ---------------------------------------------------------
    # Build Qwen chat-format input
    # ---------------------------------------------------------

    messages = [
        {
            "role": "system",
            "content": (
                "You are a controlled pharmacovigilance "
                "reporting assistant. "
                "Use only the supplied evidence. "
                "Return only the requested report section. "
                "Do not repeat the instructions."
            )
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    # ---------------------------------------------------------
    # Apply Qwen chat template
    # ---------------------------------------------------------

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    # ---------------------------------------------------------
    # Token count
    # ---------------------------------------------------------

    original_tokens = len(
        tokenizer(
            formatted_prompt,
            add_special_tokens=False
        )["input_ids"]
    )

    if original_tokens > MAX_INPUT_TOKENS:
        raise ValueError(
            f"Prompt exceeds model input limit: "
            f"{original_tokens} > {MAX_INPUT_TOKENS}"
        )

    # ---------------------------------------------------------
    # Tokenize
    # ---------------------------------------------------------

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
        truncation=False
    )

    actual_input_tokens = inputs["input_ids"].shape[1]

    print(
        f"Prompt tokens: {actual_input_tokens}"
    )

    inputs = {
        key: value.to("cpu")
        for key, value in inputs.items()
    }

    # ---------------------------------------------------------
    # Generate
    # ---------------------------------------------------------

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            num_beams=1,
            no_repeat_ngram_size=3,
            pad_token_id=tokenizer.eos_token_id
        )

    # ---------------------------------------------------------
    # IMPORTANT:
    # Remove the original prompt tokens.
    # Only decode newly generated tokens.
    # ---------------------------------------------------------

    input_length = inputs["input_ids"].shape[1]

    generated_tokens = outputs[
        0,
        input_length:
    ]

    text = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    return text.strip()


# ============================================================
# NUMBER EXTRACTION
# ============================================================

def extract_numbers(text: str) -> List[str]:
    """
    Extract numerical tokens from generated text.

    Used by the lightweight grounding validator.

    Examples:
        1024
        1,024
        91.5
        12%
    """

    if not text:
        return []

    pattern = r"""
        (?<![\w.])
        [-+]?
        \d+(?:,\d{3})*
        (?:\.\d+)?
        %?
        (?![\w.])
    """

    matches = re.findall(
        pattern,
        text,
        flags=re.VERBOSE
    )

    return [
        match.strip()
        for match in matches
    ]


# ============================================================
# NORMALIZE NUMBERS
# ============================================================

def normalize_number(number: str) -> str:
    """
    Normalize numbers so that:

        1,024 -> 1024
        90.0% -> 90.0
    """

    number = (
        number
        .replace(",", "")
        .replace("%", "")
        .strip()
    )

    try:

        value = float(number)

        if value.is_integer():

            return str(
                int(value)
            )

        return str(value)

    except ValueError:

        return number


# ============================================================
# EXTRACT EVIDENCE NUMBERS
# ============================================================

def extract_evidence_numbers(
    evidence: Any
) -> set:
    """
    Recursively extract all numerical values from
    the Evidence JSON.

    These become the allowed numerical values
    for generated text.
    """

    numbers = set()

    def recursive_extract(value):

        if isinstance(value, dict):

            for item in value.values():

                recursive_extract(item)

        elif isinstance(value, list):

            for item in value:

                recursive_extract(item)

        elif isinstance(value, (int, float)):

            numbers.add(
                normalize_number(
                    str(value)
                )
            )

        elif isinstance(value, str):

            extracted = extract_numbers(
                value
            )

            for number in extracted:

                numbers.add(
                    normalize_number(number)
                )

    recursive_extract(
        evidence
    )

    return numbers


# ============================================================
# NUMERICAL GROUNDING VALIDATION
# ============================================================

def validate_numbers(
    generated_text: str,
    evidence: Dict[str, Any]
) -> Tuple[bool, List[str]]:
    """
    Check whether numbers appearing in generated
    text exist in the Evidence JSON.

    Returns:
        valid, unsupported_numbers
    """

    generated_numbers = (
        extract_numbers(
            generated_text
        )
    )

    evidence_numbers = (
        extract_evidence_numbers(
            evidence
        )
    )

    unsupported = []

    for number in generated_numbers:

        normalized = normalize_number(
            number
        )

        if normalized not in evidence_numbers:

            unsupported.append(
                number
            )

    return (
        len(unsupported) == 0,
        unsupported
    )


# ============================================================
# UNSUPPORTED CLAIM DETECTION
# ============================================================

def detect_unsupported_claims(
    text: str
) -> List[str]:
    """
    Lightweight detection of potentially unsafe
    pharmacovigilance claims.

    This is intentionally conservative.

    A human reviewer should inspect flagged sections.
    """

    if not text:

        return [
            "Generated text is empty."
        ]

    text_lower = text.lower()

    flagged_phrases = [
    "caused by",
    "causes",
    "caused",
    "proves that",
    "confirmed safety signal",
    "confirmed signal",
    "causal relationship",
    "causally related",
    "definitively related",
    "regulatory action",
    "should be withdrawn",
    "should be discontinued",
    "should be contraindicated",
    "clinically significant safety signal",
        ]
    
    findings = []

    for phrase in flagged_phrases:

        if phrase in text_lower:

            findings.append(
                f"Potentially unsupported claim: "
                f"'{phrase}'"
            )

    return findings


# ============================================================
# SECTION VALIDATION
# ============================================================

def validate_section(
    generated_text: str,
    evidence: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Validate a generated section against evidence.

    The validator does not silently modify the model output.

    If validation fails, the section is marked
    for human review.
    """

    number_valid, unsupported_numbers = (
        validate_numbers(
            generated_text,
            evidence
        )
    )

    unsupported_claims = (
        detect_unsupported_claims(
            generated_text
        )
    )

    valid = (
        number_valid
        and len(unsupported_claims) == 0
        and bool(generated_text.strip())
    )

    return {

        "valid": valid,

        "unsupported_numbers":
            unsupported_numbers,

        "unsupported_claims":
            unsupported_claims,

        "human_review_required":
            not valid,
    }


# ============================================================
# GENERATE ONE SECTION
# ============================================================

def generate_section(
    section_name: str,
    evidence: Dict[str, Any],
    tokenizer,
    model
) -> Dict[str, Any]:
    """
    Generate and validate one report section.

    Pipeline:
        Full Evidence
            ↓
        Section-specific Evidence
            ↓
        Prompt containing Evidence
            ↓
        LLM Generation
            ↓
        Validation
            ↓
        Generation Audit
    """

    print(
        f"\nGenerating section: "
        f"{section_name}"
    )

    # ---------------------------------------------------------
    # 1. Extract only the evidence relevant to this section
    # ---------------------------------------------------------

    section_evidence = get_evidence_section(
        evidence,
        section_name
    )

    print(
        f"Evidence extracted for {section_name}:"
    )

    print(section_evidence)

    # ---------------------------------------------------------
    # 2. Build prompt using the section-specific evidence
    # ---------------------------------------------------------

    prompt = get_prompt(
        section_name,
        section_evidence
    )

    print(
        f"\nPrompt prepared for {section_name}:"
    )

    print("\n" + "=" * 70)
    print(f"PROMPT FOR: {section_name}")
    print("=" * 70)
    print(prompt)
    print("=" * 70)

    # ---------------------------------------------------------
    # 3. Generate narrative using the LLM
    # ---------------------------------------------------------

    generated_text = generate_text(
        prompt,
        tokenizer,
        model
    )

    # ---------------------------------------------------------
    # 4. Clean generated output
    # ---------------------------------------------------------

    generated_text = generated_text.strip()

    print(
        f"\nGenerated text for {section_name}:"
    )

    print(generated_text)

    # ---------------------------------------------------------
    # 5. Validate generated text against the SAME evidence
    # ---------------------------------------------------------

    validation = validate_section(
        generated_text,
        section_evidence
    )

    # ---------------------------------------------------------
    # 6. Report validation status
    # ---------------------------------------------------------

    if validation[
        "human_review_required"
    ]:

        print(
            f"WARNING: {section_name} "
            f"requires human review."
        )

        if validation[
            "unsupported_numbers"
        ]:

            print(
                "Unsupported numbers:",
                validation[
                    "unsupported_numbers"
                ]
            )

        if validation[
            "unsupported_claims"
        ]:

            print(
                "Potentially unsupported claims:",
                validation[
                    "unsupported_claims"
                ]
            )

    else:

        print(
            f"{section_name}: validation passed."
        )

    # ---------------------------------------------------------
    # 7. Return complete generation audit record
    # ---------------------------------------------------------

    return {

        "section": section_name,

        "evidence": section_evidence,

        "prompt": prompt,

        "text": generated_text,

        "validation": validation,

    }


# ============================================================
# GENERATE ALL AI SECTIONS
# ============================================================

def generate_ai_sections(
    evidence: Dict[str, Any],
    tokenizer,
    model
) -> Dict[str, Dict[str, Any]]:
    """
    Generate all sections that benefit from
    language-model interpretation.

    The master prompt recommends section-level
    generation instead of one giant LLM call.
    """

    sections = [

        "narrative_summary",

        "summary_analysis",

        "reaction_analysis",

        "serious_alert_analysis",

        "trend_interpretation",
    ]

    generated = {}

    for section in sections:

        generated[
            section
        ] = generate_section(
            section,
            evidence,
            tokenizer,
            model
        )

    return generated


# ============================================================
# DETERMINISTIC REPORT SECTIONS
# ============================================================

def format_reporting_period(
    evidence: Dict[str, Any]
) -> str:
    """
    Generate reporting period without using the LLM.
    """

    data = evidence.get(
        "reporting_period",
        {}
    )

    if not data.get("available"):

        return (
            "Reporting period information "
            "was not available in the supplied dataset."
        )

    start = data.get(
        "start_date"
    )

    end = data.get(
        "end_date"
    )

    months = data.get(
        "number_of_months"
    )

    return (
        f"The available reporting period extends "
        f"from {start} to {end}, covering "
        f"{months} month(s)."
    )


def format_case_summary(
    evidence: Dict[str, Any]
) -> str:
    """
    Deterministic case summary.
    """

    data = evidence[
        "case_summary"
    ]

    total = data[
        "total_unique_cases"
    ]

    serious = data[
        "serious_cases"
    ]

    non_serious = data[
        "non_serious_cases"
    ]

    expedite = data[
        "expedite_alert_cases"
    ]

    return (
        f"A total of {total:,} unique cases "
        f"were identified. Of these, "
        f"{serious:,} were classified as serious "
        f"and {non_serious:,} as non-serious. "
        f"{expedite:,} cases met the supplied "
        f"expedite/alert criterion."
    )


def format_methodology() -> str:
    """
    Deterministic methodology section.
    """

    return """
The analysis was performed using a deterministic
Python pipeline. The supplied ICSR dataset was
validated and cleaned before case-level and
reaction-level analyses were performed.

Case-level statistics were calculated using unique
safety report identifiers, while reaction occurrences
were analyzed separately. Missing information was
retained as unavailable/unknown where appropriate.

The resulting validated statistics were stored in
an Evidence JSON structure. A lightweight
Hugging Face Qwen2.5-0.5B-Instruct model was subsequently
used only to convert selected validated findings
into concise narrative text.

Generated content was subjected to numerical and
claim-level grounding checks and sections failing
validation were flagged for human review.
""".strip()


def format_limitations(
    evidence: Dict[str, Any]
) -> str:
    """
    Deterministic limitations section.
    """

    limitations = evidence.get(
        "limitations",
        []
    )

    if not limitations:

        return (
            "No additional limitations were "
            "identified by the deterministic "
            "analysis pipeline."
        )

    lines = [
        f"- {item}"
        for item in limitations
    ]

    return "\n".join(lines)


def format_review_status(
    generated_sections: Dict[str, Any]
) -> str:
    """
    Create human-review status based on
    section validation.
    """

    sections_requiring_review = []

    for name, result in (
        generated_sections.items()
    ):

        if result[
            "validation"
        ][
            "human_review_required"
        ]:

            sections_requiring_review.append(
                name
            )

    if sections_requiring_review:

        return (
            "**Report Status: PENDING HUMAN REVIEW**\n\n"
            "The following generated sections require "
            "human review:\n\n"
            + "\n".join(
                f"- {section}"
                for section
                in sections_requiring_review
            )
        )

    return (
        "**Report Status: PENDING HUMAN REVIEW**\n\n"
        "Automated grounding validation passed for "
        "the generated sections. Human review is still "
        "required before final approval."
    )


# ============================================================
# REPORT ASSEMBLY
# ============================================================

def assemble_report(
    evidence: Dict[str, Any],
    generated_sections: Dict[str, Any]
) -> str:
    """
    Assemble the final PADER-style Markdown report.

    Deterministic sections remain deterministic.
    LLM-generated sections are inserted only after
    validation.
    """

    narrative = generated_sections[
        "narrative_summary"
    ]["text"]

    summary_analysis = generated_sections[
        "summary_analysis"
    ]["text"]

    reaction_analysis = generated_sections[
        "reaction_analysis"
    ]["text"]

    serious_analysis = generated_sections[
        "serious_alert_analysis"
    ]["text"]

    trend_analysis = generated_sections[
        "trend_interpretation"
    ]["text"]

    report = f"""
# PADER-Style Safety Report

## 1. Reporting Period

{format_reporting_period(evidence)}

---

## 2. Narrative Summary

{narrative}

---

## 3. Case Summary

{format_case_summary(evidence)}

---

## 4. Summary Analysis

{summary_analysis}

---

## 5. Reaction Analysis

{reaction_analysis}

---

## 6. Serious and Alert Case Analysis

{serious_analysis}

---

## 7. Trend Interpretation

{trend_analysis}

---

## 8. Methodology

{format_methodology()}

---

## 9. Limitations

{format_limitations(evidence)}

---

## 10. Human Review

{format_review_status(generated_sections)}

### Review Checklist

- [ ] Analysis verified
- [ ] Generated sections reviewed
- [ ] Evidence checked
- [ ] Final report approved

---

## 11. Evidence Traceability

The report was generated from deterministic
analysis results stored in `output/evidence.json`.

The language model was not provided with the
raw ICSR Excel dataset.

Numerical and categorical analysis was performed
before language generation.

Unsupported generated content is flagged for
human review.
""".strip()

    return report


# ============================================================
# SAVE REPORT
# ============================================================

def save_report(report: str):
    """
    Save final Markdown report.
    """

    REPORT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        REPORT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(report)

    print(
        f"\nReport saved to: "
        f"{REPORT_FILE}"
    )


# ============================================================
# SAVE GENERATION AUDIT
# ============================================================

def save_generation_audit(
    generated_sections: Dict[str, Any]
):
    """
    Save generated text and validation results.

    Useful for debugging and demonstrating
    human-in-the-loop governance.
    """

    audit_file = (
        Path("output")
        / "generation_audit.json"
    )

    with open(
        audit_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            generated_sections,
            file,
            indent=2,
            ensure_ascii=False
        )

    print(
        f"Generation audit saved to: "
        f"{audit_file}"
    )


# ============================================================
# MAIN LLM PIPELINE
# ============================================================

def generate_report():
    """
    Main entry point used by main.py.

    Pipeline:

        Evidence JSON
             ↓
        Load FLAN-T5
             ↓
        Generate sections
             ↓
        Validate sections
             ↓
        Assemble report
             ↓
        Save Markdown
             ↓
        Save audit
    """

    print("\n")
    print("=" * 60)
    print("LLM REPORT GENERATION PIPELINE")
    print("=" * 60)

    # --------------------------------------------------------
    # 1. Load Evidence JSON
    # --------------------------------------------------------

    evidence = load_evidence()

    print(
        "Evidence JSON loaded successfully."
    )

    # --------------------------------------------------------
    # 2. Load model
    # --------------------------------------------------------

    tokenizer, model = load_model()

    # --------------------------------------------------------
    # 3. Generate sections
    # --------------------------------------------------------

    generated_sections = (
        generate_ai_sections(
            evidence,
            tokenizer,
            model
        )
    )

    # --------------------------------------------------------
    # 4. Assemble report
    # --------------------------------------------------------

    report = assemble_report(
        evidence,
        generated_sections
    )

    # --------------------------------------------------------
    # 5. Save report
    # --------------------------------------------------------

    save_report(
        report
    )

    # --------------------------------------------------------
    # 6. Save audit
    # --------------------------------------------------------

    save_generation_audit(
        generated_sections
    )

    # --------------------------------------------------------
    # 7. Final status
    # --------------------------------------------------------

    review_required = any(
        result[
            "validation"
        ][
            "human_review_required"
        ]
        for result
        in generated_sections.values()
    )

    print("\n")
    print("=" * 60)
    print("LLM PIPELINE COMPLETE")
    print("=" * 60)

    if review_required:

        print(
            "STATUS: HUMAN REVIEW REQUIRED"
        )

    else:

        print(
            "STATUS: AUTOMATED VALIDATION PASSED"
        )

    print(
        f"Report: {REPORT_FILE}"
    )

    return report


# ============================================================
# DIRECT EXECUTION
# ============================================================

if __name__ == "__main__":

    generate_report()